spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/local-db
  mail:
    host: mail
    port: 3025
  flyway:
    url: jdbc:postgresql://db:5432/local-db

telegram:
  baseUrl: http://wiremock:8080

selenium:
  server:
    url: http://selenium:4444

newrelic:
  enabled: false
  metrics:
    ingest-uri: http://wiremock:8080/metric/v1
