version: "3.7"

services:

  db:
    container_name: job-alerts-db
    image: postgres:13.8
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=local-db
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/data/db
    networks:
      - job-alerts-net

  mail:
    container_name: job-alerts-mail
    image: ibaiul/greenmail
    pull_policy: always
    ports:
      - "28082:8080"
      - "3025:3025"
    networks:
      - job-alerts-net

  wiremock:
    container_name: job-alerts-wiremock
    image: wiremock/wiremock:2.35.0
    ports:
      - "28081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      - job-alerts-net

  selenium:
    container_name: job-alerts-selenium
    image: selenium/standalone-firefox:120.0-geckodriver-0.33.0-grid-4.15.0-20231122
    ports:
      - "24444:4444"
      - "25900:5900"
      - "27900:7900"
#    environment:
#      - SE_OPTS="--log-level FINE"
    shm_size: 2gb
    networks:
      - job-alerts-net

  app:
    container_name: job-alerts-app
    image: ibaiul/job-alerts-local
    env_file: env.conf
    ports:
      - "28080:8080"
    depends_on:
      - db
      - mail
      - wiremock
    networks:
      - job-alerts-net

#  db-ui:
#    container_name: job-alerts-db-ui
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: password
#    ports:
#      - "25433:80"
#    volumes:
#      - pgadmin_data:/data/pgadmin
#    depends_on:
#      - db
#    logging:
#      driver: none
#    networks:
#      - job-alerts-net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  job-alerts-net:
    name: job-alerts-net
    driver: bridge